# config/services.yaml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\OpenDotaBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    GuzzleHttp\Client:

    App\OpenDotaBundle\Client\CommonClient:
        arguments:
            $apiHost: https://api.opendota.com

    GuzzleHttp\ClientInterface: '@GuzzleHttp\Client'

